# 灰階與彩色影像矩陣

### 1. 載入模組

In [1]:
# 載入模組
import numpy as np
import cv2 as cv

### 2. 灰階影像矩陣

In [6]:
# 讀取影像
img = cv.imread("./img/polystyrene.jpg")
# img = cv.imread("./img/board.jpg")

# 影像灰階化
img_gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)

# 列出影像矩陣
print(img_gray)
cv.imshow("result", img_gray)

# 按下任意鍵關閉視窗
cv.waitKey(0)
cv.destroyAllWindows() 

[[21 24 21 ... 22 22 22]
 [21 24 20 ... 22 22 22]
 [21 24 20 ... 22 22 22]
 ...
 [24 21 24 ... 26 21 39]
 [24 21 24 ... 24 21 38]
 [24 21 24 ... 23 19 36]]


### 3. 彩色影像矩陣

In [7]:
# 讀取影像 (BGR格式)
# img = cv.imread("./img/polystyrene.jpg")
# img = cv.imread("./img/board.jpg")
img = cv.imread("./img/rgb.png")

# 影像BGR轉RGB
# img_rgb = cv.cvtColor(img, cv.COLOR_BGR2RGB)

# 列出影像矩陣
print(img)
cv.imshow("result", img)

# 按下任意鍵關閉視窗
cv.waitKey(0)
cv.destroyAllWindows() 

[[[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0   0 255]
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]
  [  0 255   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]
  [255   0   0]]

 [[  0   0 255]
  [  0   0 255